add: sports_landing_page
DhanushNehru/Ultimate-Web-Development-Resources pull request #564
Opened 2024-10-10 09:38 UTC by damarudhvarma

I've created a sports landing page  of an random academy  with a nice UI

2024-10-12 18:45 UTC, damarudhvarma commented
@DhanushNehru  please review this PR and Add hacktoberfest 2024 labels

2024-10-13 10:53 UTC, DhanushNehru approved these changes

2024-10-13 10:54 UTC, DhanushNehru requested changes
Hi @damarudhvarma dont comment the .env file. It can be added as part of the project readme to include it

2024-10-13 12:06 UTC, damarudhvarma commented
@DhanushNehru i've deleted the .env file and created the readme.md file checkout and merge this branch and add  hactoberfest labels.  issue #566 resolved

2024-10-16 05:50 UTC, DhanushNehru approved these changes

2024-10-16 05:50 UTC, merged